name: pack

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - name: Upload packed crx
        uses: actions/upload-artifact@v2
        with:
          name: "netease-music-crx-plus-*.zip"
          path: "./"
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.AUTOMATIC_RELEASE_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
